version: '3'

services:
  web:
    build:
      context: .
      dockerfile: docker/golang/Dockerfile
    ports:
      - 8080:8080
    volumes:
      - .:/golang-docker
    depends_on:
      - database
    container_name: golang-docker-web

  database:
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    container_name: golang-docker-db
    ports:
      - 3306:3306
    volumes:
      - golang-docker-data:/var/lib/mysql

volumes:
  golang-docker-data: